### ISSUE TITLE
[Bug]: Pimcore 10 pagination issue on dashboard custom reports #11779

### ISSUE THREAD

**Issue by evanjamesjackson** [TorqIT/pimcore#1]
https://github.com/pimcore/pimcore/issues/11779

**Comment by cameronfromtorq** [comment]
![image](https://user-images.githubusercontent.com/105230931/200860471-64f3161a-5ff2-4ade-89dc-7293ba167158.png)

![image](https://user-images.githubusercontent.com/105230931/200860593-52109a88-31f7-473c-af46-af3a28cdae98.png)

now adds scrollbar when needed
