### ISSUE TITLE
[Bug][DataObject][GridFilter] Filtered Relation Fields are not highlighted with italic header #12243

### ISSUE THREAD

**Issue by evanjamesjackson** [TorqIT/pimcore#2]
https://github.com/pimcore/pimcore/issues/12243

**Comment by cameronfromtorq** [comment]
finding this hard to reproduce 


![Image](https://user-images.githubusercontent.com/105230931/200390473-e93937cc-29d1-466c-8782-f8f230e44bd4.png)

none of the columns appear italicized
