### ISSUE TITLE
[Bug]: The UI for chosing objectbrick when adding in object is not responsive #13743

### ISSUE THREAD

**Issue by lukemacausland** [TorqIT/pimcore#22]
https://github.com/pimcore/pimcore/issues/13743

Thinking we can add a scroll bar, and than at the top have an input field where the user can type / filter the options.

**Comment by cameronfromtorq** [comment]
![image](https://user-images.githubusercontent.com/105230931/208305714-4f84cf39-0bcf-4f31-908b-62cffcabcb2c.png)
seems to me like this issue is no longer present.
I confirmed that all bricks are accounted for using the existing (not the best) scroll functionality. 

@lukemacausland
