### ISSUE TITLE
[Bug]: Glossary not working with pimcore_wysiwyg content #13793

### ISSUE THREAD

**Issue by lukemacausland** [TorqIT/pimcore#24]
https://github.com/pimcore/pimcore/issues/13793

**Comment by lukemacausland** [comment]
Look into this issue and see if we can replicate it.

**Comment by dvesh3** [comment]
Hi, this is an invalid issue. please see https://github.com/pimcore/pimcore/issues/13793#issuecomment-1361277983

**Comment by lukemacausland** [comment]
Thanks for letting us know @dvesh3
