### ISSUE TITLE
[Bug]: Web2Print - "active-generate-process": Method Not Allowed #13717

### ISSUE THREAD

**Issue by lukemacausland** [TorqIT/pimcore#25]
https://github.com/pimcore/pimcore/issues/13717

This can be replicated in the pimcore demo environment. Open a document, click generate pdf - stuck at 0%, and network tab sends multiple requests.

**Comment by PMD-TorqIT** [comment]
@lukemacausland I think that they may have fixed it as I ran some tests with their demo site, and it seems to work correctly now.
