### ISSUE TITLE
[Bug]: Grid Option window: top border hidden #11986

### ISSUE THREAD

**Issue by evanjamesjackson** [TorqIT/pimcore#4]
https://github.com/pimcore/pimcore/issues/11986

**Comment by cameronfromtorq** [comment]
I have made it so the header cannot leave the top of the page. unfortunatly the change also makes it so it cannot leave the sides of the page. Let me know if this can be a feature bug or if I need to keep investigating @evanjamesjackson .
![image](https://user-images.githubusercontent.com/105230931/200851323-fcf4d7e4-0dd4-4fcf-a9b6-7b1d28c383de.png)

**Comment by cameronfromtorq** [comment]
@lukemacausland do you think the window should/needs to have the ability to go off the side of the page? Nothing behind the window is usable anyway.

**Comment by lukemacausland** [comment]
> I have made it so the header cannot leave the top of the page. unfortunatly the change also makes it so it cannot leave the sides of the page. Let me know if this can be a feature bug or if I need to keep investigating @evanjamesjackson . ![image](https://user-images.githubusercontent.com/105230931/200851323-fcf4d7e4-0dd4-4fcf-a9b6-7b1d28c383de.png)

Hmm, I was thinking it would be nice to still be able to allow at least the sides to leave the page. But I don't think that will really help the user anyways since its a modal popup. So I think that is probably fine (we can see what pimcore thinks of it, or maybe even comment on the post showing our solution). What happens if the screen is very small, it still works fine?

**Comment by lukemacausland** [comment]
@cameronfromtorq

**Comment by cameronfromtorq** [comment]
hmm thats a good point, it prioritizes the left constraint of the window so if the browser is too small, you cant see the right side of the popup window. (you can still do a hacky thing where you resize the popup from the left side as to fit on the screen:)
![image](https://user-images.githubusercontent.com/105230931/200867161-ef581bd0-0d5e-46fe-ab97-d9e1fede2f71.png)

**Comment by lukemacausland** [comment]
Hmm would the overflow option fix that? We can always hop on a call if you'd like to discuss it a bit more.
