### ISSUE TITLE
[Bug]: Composite indices failing to save for relation data type #12060

### ISSUE THREAD

**Issue by evanjamesjackson** [TorqIT/pimcore#5]
https://github.com/pimcore/pimcore/issues/12060

**Comment by lukemacausland** [comment]
![Image](https://user-images.githubusercontent.com/58705994/200328086-d998cf21-439c-4849-bac9-1649d770a0bc.png)

**Comment by lukemacausland** [comment]
![Image](https://user-images.githubusercontent.com/58705994/200328183-90b01005-de23-461b-9bea-48d1ab0a76eb.png)

**Comment by lukemacausland** [comment]
Evan suggested we should just show the following fields instead of just Group



![Image](https://user-images.githubusercontent.com/58705994/200328422-c0d6baa8-0ce0-4b66-a9c2-cc4d84a44be1.png)
