### ISSUE TITLE
[Bug]: Cannot retain slash at the end of the URL on link editable under Documents

### ISSUE THREAD

**Issue by cameronfromtorq** [TorqIT/pimcore#54]
https://github.com/pimcore/pimcore/issues/14375

maybe we could add a symfony expression in the properties tab for string manipulations of the url.

**Comment by lukemacausland** [comment]
@cameronfromtorq - https://github.com/pimcore/pimcore/pull/14898

**Comment by lukemacausland** [comment]
Closing as pimcore decided this wasn't a good idea.
